version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
    open-pull-requests-limit: 10
    groups:
      aspire:
        patterns:
          - "Aspire"
          - "Aspire.*"
      dotnet:
        patterns:
          - "Microsoft.*"
          - "System.*"
      open-telemetry:
        patterns:
          - "OpenTelemetry.*"
      temporal:
        patterns:
          - "Temporalio"
          - "Temporalio.*"
