<Project Sdk="Microsoft.NET.Sdk">
  <Sdk Name="Aspire.AppHost.Sdk" Version="9.0.0" />
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsAspireHost>true</IsAspireHost>
    <IsPackable>false</IsPackable>
    <UserSecretsId>102B9DBC-01A4-4DAB-8530-6B9E3C10C956</UserSecretsId>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.AppHost"/>
    <PackageReference Include="InfinityFlow.Aspire.Temporal"/>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" VersionOverride="10.0.2" />
    <PackageReference Include="Microsoft.Extensions.Hosting" />
    <ProjectReference Include="..\..\..\test\Worker\InfinityFlow.Temporal.Migrator.Tests.Worker.csproj" />
  </ItemGroup>
</Project>
