name: Release Drafter

on:
  push:
    branches:
      - main
  pull_request_target:
    types:
      - edited
      - opened
      - reopened
      - synchronize
  workflow_dispatch:
    inputs:
      release-type:
        type: choice
        default: prerelease
        description: Release Type
        options:
          - release
          - prerelease

concurrency:
  group: ${{ github.event_name == 'pull_request' && format('pr-{0}', github.event.number) || github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' && github.ref_type != 'tag' }}

jobs:
  update_release_draft:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: "Draft Release"
        uses: release-drafter/release-drafter@v6.0.0
        with:
          prerelease: ${{ github.event.inputs.release-type != 'release' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
